import Vue from 'vue'
import Vuetify, {
  VApp,
  VNavigationDrawer,
  VLayout,
  VContainer,
  VContent,
  VSpacer,
  VFlex,
  VFooter,
  VList,
  VListGroup,
  VListTile,
  VListTileContent,
  VListTileTitle,
  VListTileSubTitle,
  VBtn,
  VIcon,
  VToolbar,
  VToolbarTitle,
  VToolbarItems,
  VToolbarSideIcon,
  VCard,
  VCardTitle,
  VCardText,
  VCardActions,
  VSubheader,
  VTextField,
  VCheckbox,
  VDialog,
  VSelect,
  VDivider,
  VForm,
  VChip,
  VAlert,
  VProgressLinear,
  VDataTable,
  VSnackbar,
  VMenu,
  VAvatar,
  VImg,
  VProgressCircular,
  VLabel,
  VStepper,
  VStepperHeader,
  VStepperStep,
  VStepperItems,
  VStepperContent,
  VAutocomplete,
  VParallax,
  VTooltip,
  VBtnToggle,
  VSwitch,
  VTextarea,
  VTabs,
  VTab,
  VTabsItems,
  VTabItem,
  VBottomSheet,
  VBadge,
  VCarousel,
  VCarouselItem,
  VPagination,
  VSlideYTransition
} from 'vuetify/lib'
// import 'vuetify/src/stylus/app.styl'
import { Resize } from 'vuetify/lib/directives'
Vue.use(Vuetify, {
  components: {
    VApp,
    VNavigationDrawer,
    VLayout,
    VContainer,
    VContent,
    VSpacer,
    VFlex,
    VFooter,
    VList,
    VListGroup,
    VListTile,
    VListTileContent,
    VListTileTitle,
    VListTileSubTitle,
    VBtn,
    VIcon,
    VToolbar,
    VToolbarTitle,
    VToolbarItems,
    VToolbarSideIcon,
    VCard,
    VCardTitle,
    VCardText,
    VCardActions,
    VSubheader,
    VTextField,
    VCheckbox,
    VDialog,
    VSelect,
    VDivider,
    VForm,
    VChip,
    VAlert,
    VProgressLinear,
    VDataTable,
    VSnackbar,
    VMenu,
    VAvatar,
    VImg,
    VProgressCircular,
    VLabel,
    VStepper,
    VStepperHeader,
    VStepperStep,
    VStepperItems,
    VStepperContent,
    VAutocomplete,
    VParallax,
    VTooltip,
    VBtnToggle,
    VSwitch,
    VTextarea,
    VTabs,
    VTab,
    VTabsItems,
    VTabItem,
    VBottomSheet,
    VBadge,
    VCarousel,
    VCarouselItem,
    VPagination,
    VSlideYTransition
  },
  directives: {
    Resize
  },
  theme: {
    primary: '#3F51B5',
    secondary: '#424242',
    accent: '#82B1FF',
    error: '#FF5252',
    info: '#2196F3',
    success: '#4CAF50',
    warning: '#FFC107'
  },
  customProperties: true,
  iconfont: 'md',
  lang: {
    locales: {
      'ko': {
        'dataIterator': {
          'rowsPerPageText': '페이지당 ',
          'rowsPerPageAll': '전체보기',
          'pageText': '{0}-{1}, 전체 {2}건',
          'noResultsText': '표시할 항목이 없습니다.',
          'nextPage': '다음',
          'prevPage': '이전'
        },
        'dataTable': {
          'rowsPerPageText': '페이지당 '
        },
        'noDataText': '표시할 항목이 없습니다.'
      }
    },
    current: 'ko'
  }
})
